camunda:
  bpm:
    admin-user:
      id: fogorvosdemo
      password: fogorvosdemo
      first-name: Demo
    filter:
      create: All tasks
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fogorvos_camunda
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update

peczedavid:
  app:
    jwtSecret: zt4PMzDXJHyX4iVaVHK5ZWF21GPSDjQUJq1gPBh6pUaJjMjxWah1QhT9Yt3EiG1
    jwtCookieName: jwtCookie
    jwtExpirationMs: 86400000
